
# Uncomment this line to define a global platform for your project
platform :ios, '12.0'
# Uncomment this line if you’re using Swift
use_frameworks!


target "blitz" do
  pod 'StripeTerminal', '1.0.0-b5'
end


