
# Uncomment this line to define a global platform for your project
platform :ios, '12.0'
# Uncomment this line if you’re using Swift
use_frameworks!


target "blitz" do
  pod 'StripeTerminal', '1.0.0-b5'
  pod 'react-native-blur', :path => '../node_modules/react-native-blur'

  pod 'react-native-fast-image', :path => '../node_modules/react-native-fast-image'

end


