# Uncomment the next line to define a global platform for your project
platform :ios, '12.2'

target 'kiosk' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!

  # Pods for kiosk
  pod 'StripeTerminal', '1.0.0-b6'
  
end
